---
version: '2'
services:
  postgres:
    image: postgres:16
    container_name: postgres
    hostname: postgres
    restart: always
    expose:
      - 5432
    ports:
      - "5436:5432/tcp"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=appDB
      - POSTGRES_HOST_AUTH_METHOD=trust
  auth:
    image: auth:latest
    container_name: auth
    hostname: auth
    build:
      context: ./back/authentification
      dockerfile: Dockerfile
    ports:
      - "8882:8083"
    depends_on:
      - postgres
      - config-server
  order:
    image: order:latest
    container_name: order
    hostname: order
    build:
      context: ./back/order
      dockerfile: Dockerfile
    ports:
      - "8883:8083"
    depends_on:
      - postgres
      - config-server
  payment:
    image: payment:latest
    container_name: payments
    hostname: payment
    build:
      context: ./back/payments
      dockerfile: Dockerfile
    ports:
      - "8884:8083"
    depends_on:
      - postgres
      - config-server
  product:
    image: product:latest
    container_name: product
    hostname: product
    build:
      context: ./back/product
      dockerfile: Dockerfile
    ports:
      - "8885:8083"
    depends_on:
      - postgres
      - config-server
  eureka:
    image: eureka:latest
    container_name: eureka
    hostname: eureka
    build:
      context: ./back/eureka
      dockerfile: Dockerfile
    ports:
      - "8886:8083"
    depends_on:
      - postgres
      - config-server
  config-server:
    image: config-server:latest
    container_name: config-server
    hostname: config-server
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - postgres