spring:
  application:
    name: eureka # Assurez-vous que ceci est le nom de votre application cliente, pas simplement 'eureka'
  config:
    import: "optional:configserver:http://localhost:8888"

server:
  port: 8888

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false