spring:
  application:
    name: eureka # Assurez-vous que ceci est le nom de votre application cliente, pas simplement 'eureka'
  config:
    import: "optional:configserver:http://config-server:8888"