spring:
  application:
    name: authentification  # Nom de l'application
  cloud:
    config:
      uri: http://config-server:8888  # URL du serveur de configuration
  profiles:
    active: default  # Profil actif