spring:
  application:
    name: product  # Nom de l'application
  cloud:
    config:
      uri: http://config-server:8888  # URL du serveur de configuration
  profiles:
    active: default  # Profil actif

  config:
    import: "configserver:http://config-server:8888"  # Importation de la configuration du serveur de config
