# Spring Cloud Config application.yml
server:
  port: 8888 # le port de Spring Cloud Config
spring:
  cloud:
    config:
      server:
        git:
          uri: file:///Users/gleca/IdeaProjects/EdgeMs/config-repo/