# Spring Cloud Config application.yml
server:
  port: 8888 # le port de Spring Cloud Config
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Elogrz/EdgeMs.git
          default-label: main
          token : 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