spring:
  application:
    name: zuul
  cloud:
    config:
      uri: http://config-server:8888
  profiles:
    active: development
  
  config:
    import: "configserver:http://config-server:8888"  # Importation de la configuration du serveur de config
