<<<<<<< HEAD
<<<<<<< HEAD
spring:
  application:
    name: zuul
  cloud:
    config:
      uri: http://config-server:8888
  profiles:
    active: development
  
  config:
    import: "configserver:http://config-server:8888"  # Importation de la configuration du serveur de config
=======
=======
>>>>>>> 15d5ab7c9709316ff6b3ec62427b08f2cbb528a5
spring:
  application:
    name: zuul
  cloud:
    config:
      uri: http://config-server:8888
  profiles:
    active: development
  
  config:
    import: "configserver:http://config-server:8888"  # Importation de la configuration du serveur de config
<<<<<<< HEAD
>>>>>>> b613d12 (final client + ZUUUUUL 1)
=======
>>>>>>> 15d5ab7c9709316ff6b3ec62427b08f2cbb528a5
