eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

custom:
  http:
    config:
      url: "https://Elogrz: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@github.com/Elogrz/EdgeMs.git"

spring:
  cloud:
    config:
      import-check:
        enabled: false
  application:
    name: product
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://postgres:5436/appDB
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8083
